[package]

name = "common"
version = "0.0.1"
authors = ["Andrey Demin <ademinn@gmail.com>"]

[dependencies.GSL]

git = "https://github.com/GuillaumeGomez/rust-GSL.git"

[lib]

name = "common"
path = "lib.rs"
